### ISSUE TITLE
Make gitrekt into a standalone package

### ISSUE THREAD

**Issue by beta-phenylethylamine** [almightycouch/gitgud#38]
Would be useful for people interested in implementing a git server component into their own projects.

Currently depending on gitrekt is a bit of a mess for a project, as you would have to first clone gitgud and then add the dependency based on its path since gitgud is an umbrella project, which is unintuitive and fairly unportable without using something like submodules, which no one wants to do for their project

**Comment by beta-phenylethylamine** [comment]
Alternatively, you could just upload it to hex.pm since that doesn't depend on packages being in the git root, although I could understand if you'd prefer not to upload an unfinished package to it

**Comment by redrabbit** [comment]
Hi @beta-phenylethylamine,

> Would be useful for people interested in implementing a git server component into their own projects.

Yes, it would be very nice to have a plug-and-play Git backend you could drop as a project dependency. In it current state GitGud does not provide a simple way to do so out of the box.

The project is currently split into three main components (umbrella application):

* `:gitrekt` -- low-level Git functions and implementations of Git [wire protocol](https://git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols) and [*PACK* format](https://git-scm.com/docs/pack-format).
* `:gitgud` -- is the core application providing most critical building blocks.
  * database schemas such as [`GitGud.User`](https://almightycouch.com/gitgud/GitGud.User.html) and [`GitGud.Repo`](https://almightycouch.com/gitgud/GitGud.Repo.html).
  * [authorization](https://almightycouch.com/gitgud/GitGud.Authorization.html) and conveniences for resource loading and viewability.
  * higher-level Git functionalities (see [`GitGud.GitCommit`](https://almightycouch.com/gitgud/GitGud.GitCommit.html) for example).
  * Git [SSH server](https://almightycouch.com/gitgud/GitGud.SSHServer.html) and [HTTP plug](https://almightycouch.com/gitgud/GitGud.SmartHTTPBackend.html) for handling `fetch` and `push` request from Git clients.
* `:gitgud_web` -- Web frontend and GraphQL API, using [Phoenix](https://phoenixframework.org) and [Absinthe](https://absinthe-graphql.org).

Publishing `:gitrekt` on it own means that people would still have to implement a lot (Git transport protocols, SSH, HTTP), authentication, authorization, database schemas to work with etc.

One possibility would be to drastically refactor `:gitrekt` in order to include SSH and HTTP transport protocols and provide a flexible way  (config files?, macros?) to let people use their own structs and endpoints to handle authentication, authorization, etc.

An other possibility with the current *project structure*, would be to publish all three components as separate Hex packages with a dependency hierarchy between the packages looking as follow:

    :gitrekt <- :gitgud <- :gitgud_web

People could use `:gitrekt` and implement things on their own, or use `:gitgud` in order to have more built-in feature or even `:gitgud_web` for the whole shebang.

> Alternatively, you could just upload it to hex.pm since that doesn't depend on packages being in the git root, although I could understand if you'd prefer not to upload an unfinished package to it

If I remember correctly, Hex does not support publishing umbrella application.

Also, the project is approaching *version 0.2* and for me it is not polished enough to be published as package. I would rather continue to work with the current umbrella application where I have more flexibility over all components (not having to care about breaking API changes between package versions, etc.).
